apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: files-yogram-production-config-secret
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: files-yogram-production-config-secret
                  key: AWS_REGION
            - name: RMQ_URL
              valueFrom:
                secretKeyRef:
                  name: files-yogram-production-config-secret
                  key: RMQ_URL
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: files-yogram-production-config-secret
                  key: AWS_ACCESS_KEY
