apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER
          env:
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: PAYPAL_SECRET
            - name: USERS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: USERS_SERVICE_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: REDIS_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: REDIS_PORT
            - name: TIME_PERIOD
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: TIME_PERIOD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: REDIS_USER
            - name: BUSINESS_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: BUSINESS_SERVICE_URL
            - name: POSTGRES_TYPE
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: POSTGRES_TYPE
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: POSTGRES_URL
            - name: PROFILE_SETTINGS_PAGE
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: PROFILE_SETTINGS_PAGE
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: business-yogram-production-config-secret
                  key: PAYPAL_CLIENT_ID
