apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME
  namespace: NAMESPACE
  labels:
    app: PROJECT
spec:
  selector:
    matchLabels:
      project: PROJECT
  template:
    metadata:
      namespace: NAMESPACE
      labels:
        project: PROJECT
    spec:
      containers:
        - name: PROJECT
          image: REGISTRY_HOSTNAME/PROJECT:TAG_VERSION
          ports:
            - containerPort: PORT_CONTAINER

          env:
            - name: POSTGRES_TYPE
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: POSTGRES_TYPE
            - name: POSTGRES_MIGRATION_TABLE
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: POSTGRES_MIGRATION_TABLE
            - name: SYNCHRONIZE
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: SYNCHRONIZE
            - name: AUTOLOAD_ENTITIES
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: AUTOLOAD_ENTITIES
            - name: DROP_SCHEMA
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: DROP_SCHEMA
            - name: RMQ_URL
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: RMQ_URL
            - name: FILES_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: FILES_SERVICE_URL
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: BUCKET
            - name: FILES_SERVICE_POSTS_UPLOAD_PATH
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: FILES_SERVICE_POSTS_UPLOAD_PATH
            - name: FILES_SERVICE_CHUNKS_DIR
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: FILES_SERVICE_CHUNKS_DIR
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: posts-yogram-production-config-secret
                  key: POSTGRES_URL
