export enum HttpUsersPath {
  Create = 'users/create',
  Update = 'users/update',
  CreateWithGoogle = 'users/google',
  FindUserByCriteria = 'users',
  FindUserByProviderId = 'users/findone',
  FindProviderByProviderId = 'users/provider',
  EmailVerify = 'users/email-verify',
  UpdateUserByCriteria = 'users/update',
  Subscribe = 'users/subscribe',
  Unsubscribe = 'users/unsubscribe',
  GetAllSubscribedOn = 'users/subscriptions',
  GetAllSubscribers = 'users/subscribers',
  GetAvatars = 'users/avatars',
  SwitchAvatar = 'users/avatar/switch',
  DeleteAvatar = 'users/:id/avatar/delete',
  Amount = 'users/amount',
}
