export enum HttpUsersPath {
  Create = 'users/create',
  Update = 'users/update',
  CreateWithGoogle = 'users/google',
  FindUserByCriteria = 'users',
  FindUserByProviderId = 'users/findone',
  FindProviderByProviderId = 'users/provider',
  EmailVerify = 'users/email-verify',
  UpdateUserByCriteria = 'users/update',
  Subscribe = 'users/subscribe',
  Unsubscribe = 'users/unsubscribe',
  GetAllSubscribedOn = 'users/subscriptions',
  GetAvatars = 'users/avatars',
  SwitchAvatar = 'users/switch-avatar',
}
